meta_product_name: "Dream Om"
meta_title: "Dream Om- Build Your Dream Home"
meta_description: "Let us, help you, make your dream, come true"
meta_image: "cover2.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
